# Copyright (c) 2021 Jesse N. <jesse@keplerdev.com>
# This work is licensed under the terms of the MIT license. For a copy, see <https://opensource.org/licenses/MIT>.

export EDITOR=nano
export LANG=en_US.UTF-8
export FUNCTIONS_CORE_TOOLS_TELEMETRY_OPTOUT=1
export RUNNING_IN_DOCKER="true"

# Oh my zsh
export ZSH="$HOME/.oh-my-zsh"
export ZSH_THEME="agnoster"
export HYPHEN_INSENSITIVE="true"
export DISABLE_AUTO_UPDATE="true"
export ENABLE_CORRECTION="true"
export COMPLETION_WAITING_DOTS="true"
export HIST_STAMPS="yyyy-mm-dd"

plugins=(

)
