# Copyright (c) 2021 - 2022 Jesse N. <jesse@keplerdev.com>
# This work is licensed under the terms of the MIT license. For a copy, see <https://opensource.org/licenses/MIT>.

# shellcheck shell=bash
# shellcheck source-path=SCRIPTDIR
# shellcheck enable=quote-safe-variables
# shellcheck enable=check-unassigned-uppercase
# shellcheck disable=SC2034,SC2016,SC1091

autoload -Uz promptinit
promptinit
setopt histignorealldups sharehistory 
bindkey -e

export HISTSIZE=100000
export SAVEHIST=1000000
export HISTFILE="$HOME/.zsh_history"

autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

export COMMON="/home/.common";

if [ -f "$COMMON/zsh/zshenv.zsh" ]; then
    source "$COMMON/zsh/zshenv.zsh";
fi

if [ -f "$COMMON/zsh/zshaliases.zsh" ]; then
    source "$COMMON/zsh/zshaliases.zsh";
fi

if [ -f "$ZSH/oh-my-zsh.sh" ]; then
    source "$ZSH/oh-my-zsh.sh";
fi

alias edit-zshconfig="$EDITOR ~/.zshrc";
alias edit-ohmyzsh="$EDITOR $ZSH/oh-my-zsh";
alias src-ohmyzsh="source $COMMON/zsh/zshrc.ohmyzsh.zsh";
alias src-zshrc="source $HOME/.zshrc";
